[common]
server_addr = 51.68.224.131
server_port = 7000
reuse_port = true

# Port principal utilisé par Remote Play (TCP)
[ps4_tcp_9295]
type = tcp
local_ip = 192.168.1.134
local_port = 9295
remote_port = 9295

# Port principal utilisé par Remote Play (UDP)
[ps4_udp_9295]
type = udp
local_ip = 192.168.1.134
local_port = 9295
remote_port = 9295

# Autres ports UDP recommandés
[ps4_udp_9296]
type = udp
local_ip = 192.168.1.134
local_port = 9296
remote_port = 9296

[ps4_udp_9297]
type = udp
local_ip = 192.168.1.134
local_port = 9297
remote_port = 9297

[ps4_udp_9303]
type = udp
local_ip = 192.168.1.134
local_port = 9303
remote_port = 9303

